steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/dify-sandbox/langgenius/dify-sandbox:${_DIFY_SANDBOX_VERSION}'
      - '.'
    env:
      - 'DIFY_SANDBOX_VERSION=${_DIFY_SANDBOX_VERSION}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/dify-sandbox/langgenius/dify-sandbox:${_DIFY_SANDBOX_VERSION}'

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/dify-sandbox/langgenius/dify-sandbox:${_DIFY_SANDBOX_VERSION}'
